apps/main/urls.py
from django.urls import path
from .views import HomeView, PageDetailView


app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('<slug:slug>', PageDetailView.as_view(), name='page'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import path, include
from {{ project_name }} import settings
from django.conf.urls.static import static
from {{ project_name }}.sitemap import StaticSitemap, PageSitemap, HtmlMapView, RobotsView
from django.contrib.sitemaps.views import sitemap


sitemaps = {
    'static':   StaticSitemap,
    'pages': PageSitemap,
}

seo_urlpatterns = [
    path('robots.txt', RobotsView.as_view()),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    path('sitemap.html', HtmlMapView.as_view(), name="html_map"),
]


apps_urlpatterns = [
    path('', include('apps.main.urls', namespace="main")),

]

third_apps_urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns = seo_urlpatterns + apps_urlpatterns + third_apps_urlpatterns

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls))

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns

apps/main/models.py
from django.db import models


TEMPLATES = (
    ('default.html', 'default'),
    ('home.html', 'home'),
)


class PageManager(models.Manager):
    def get_home_page(self):
        try:
            return super().get(slug='home')
        except models.ObjectDoesNotExist:
            return None


class Page(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    sort = models.SmallIntegerField(default=1)
    template = models.CharField(max_length=100, choices=TEMPLATES)
    content = models.TextField(max_length=10000, blank=True)
    meta_keywords = models.CharField( max_length=100, blank=True)
    meta_description = models.TextField(max_length=400, blank=True)
    meta_tags = models.TextField(max_length=400, blank=True)
    scripts = models.TextField(max_length=500, blank=True)

    objects = PageManager()

    class Meta:
        ordering = ['sort', 'id']

    def __str__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return 'main:page', (self.slug,)

    def get_template(self):
        return 'main/%s' % self.template

apps/main/views.py
from django.views.generic import TemplateView, DetailView
from .models import Page


class HomeView(TemplateView):
    template_name = 'main/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page'] = Page.objects.get_home_page()
        return context


class PageDetailView(DetailView):
    model = Page

    def get_template_names(self):
        return self.object.get_template()

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block meta %}
        {% include 'base_includes/meta.html' %}
    {% endblock %}


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='shortcut icon' type='image/x-icon' href="{% static 'img/favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
{% include 'base_includes/header.html' %}
{% block second_header %}
{% endblock %}

<div class="container content">
    {% include 'includes/messages.html' %}
    {% block content %}
    {% endblock %}
</div>


{% include 'base_includes/footer.html' %}
<script
        src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"
></script>

<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
></script>
<script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
></script>

{% block scripts %}
{% endblock %}

</body>
</html>

templates/base_includes/header.html
{% load main_tags %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'main:home' %}"> {{ project_name }} </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">


        <ul class="navbar-nav mr-auto">
            {% url 'main:home' as url %}
            <li class="nav-item ">
                <a class="nav-link {% is_url_active url %}" href="{{ url }}">Home</a>
            </li>
            {% for page in pages %}
                {% url 'main:page' page.slug as url %}
                <li class="nav-item ">
                    <a class="nav-link {% is_url_active url %}" href="{{ url }}">{{ page.title }}</a>
                </li>
            {% endfor %}
        </ul>

        <ul class="navbar-nav">
        </ul>

    </div>
</nav>

templates/base_includes/meta.html
<title>
    {% if page %}
        {% if page.meta_title %}
            {{ page.meta_title|safe }}
        {% else %}
            {{ page.title }}
        {% endif %}
    {% else %}

    {% endif %}
</title>
<meta name="keywords" content="
      {% if page.meta_keywords %}
        {{ page.meta_keywords }}
      {% endif %}
    ">
<meta name="description" content="
      {% if page.meta_description %}
        {{ page.meta_description }}
      {% endif %}
    ">
{{ page.meta_tags|safe }}

templates/includes/form_default.html
{% load main_tags %}

{% if form.errors %}
    {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-3 ">
                {{ field.label }}:
            </label>
            {% if field.errors %}
                {{ field|add_class:'form-control col-6 is-invalid'}}
            {% else %}
                {{ field|add_class:'form-control col-6 is-valid'}}
            {% endif %}

            {% for error in field.errors %}
                <div class="invalid-feedback col-12">
                    {{ error }}
                </div>
            {% endfor %}

            {% if field.help_text %}
                <small class="text-muted col-12">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
    {% endfor %}
{% else %}
    {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-3">{{ field.label }}:</label>
            {{ field|add_class:'form-control col-6'}}
            {% if field.help_text %}
                <small class="text-muted col-12">{{ field.help_text|safe }}</small>
            {% endif %}
        </div>
    {% endfor %}
{% endif %}

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
             <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
    {% endfor %}
{% endif %}

{#message for ajax#}
<div style="display: none; position: fixed; right: 0" class="alert ajax-alert  alert-dismissible fade show" role="alert">
    <strong class="text-center"></strong>
</div>

templates/includes/pagination.html
{% if page_obj.has_other_pages %}
    <div class="row">
        <div class="col-12">
                {% if page_obj.has_previous %}
                    <a class="badge badge-info" href="?page=1">&laquo;</a>
                    <a class="badge badge-info" href="?page={{ page_obj.previous_page_number }}"><-</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a class="badge badge-info" href="?page={{ page_obj.next_page_number }}">-></a>
                    <a class="badge badge-info" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                {% endif %}
        </div>
    </div>
{% endif %}

templates/main/default.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">{{ page.title }}</h1>
    {{ page.content|safe }}
{% endblock %}

templates/main/home.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">{{ page.title }}</h1>
    {{ page.content|safe }}
{% endblock %}

templates/sitemap.html
{% extends 'base.html' %}


{% block title %}Site Map{% endblock %}



{% block content %}
    <h1>Site Map</h1>
    <div>
        <p><a href="{% url 'main:home' %}">Home</a></p>
        {% for item in pages %}
            <p><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></p>
        {% endfor %}
    </div>

{% endblock %}